export const sliderItems = [
  {
    id: 1,
    image: "https://theguitarstore.s3.ap-south-1.amazonaws.com/new-models.jpg",
    title: "NEW MODELS RELEASED",
    description: "NEW OPTIONS. NO LIMITS.",
  },
  {
    id: 2,
    image: "https://theguitarstore.s3.ap-south-1.amazonaws.com/strings.jpg",
    title: "D'Addario Strings ",
    description: "Coming soon",
  },
  {
    id: 3,
    image: "https://theguitarstore.s3.ap-south-1.amazonaws.com/00.jpg",
    title: "THE NEW 00-28 MODERN DELUXE",
    description: "OUR FLAGSHIP SERIES",
  },
];

export const categories = [
  {
    id: 1,
    image:
      "https://theguitarstore.s3.ap-south-1.amazonaws.com/little-series.png",
    title: "LITTLE SERIES",
    description:
      "Worry-free durability, amazing portability and sound great anywhere.",
    category: "little-series",
  },
  {
    id: 2,
    image: "https://theguitarstore.s3.ap-south-1.amazonaws.com/x-series.png",
    title: "X SERIES",
    description:
      "Made for musicians that want the freedom to play how, where, and when they want without breaking the bank.",
    category: "x-series",
  },
  {
    id: 3,
    image:
      "https://theguitarstore.s3.ap-south-1.amazonaws.com/standard-series.png",
    title: "STANDARD SERIES",
    description:
      "Two centuries of craftsmanship and technique—history made from wood and wire.",
    category: "standard-series",
  },
  {
    id: 4,
    image:
      "https://theguitarstore.s3.ap-south-1.amazonaws.com/modern-deluxe-series.png",
    title: "MODERN DELUXE",
    description:
      "The look, tone, and construction of vintage Martin guitars with modern features. ",
    category: "modern-deluxe-series",
  },
  {
    id: 5,
    image: "https://theguitarstore.s3.ap-south-1.amazonaws.com/accessories.png",
    title: "ACCESSORIES",
    description: "Coming Soon",
  },
];

export const products = [
  {
    id: 1,
    image:
      "https://theguitarstore.s3.ap-south-1.amazonaws.com/little-series/LX1.jpg",
    title: "LX1",
    series: "Little Series",
    price: "$159",
    specs: [
      {
        bodysize: "0-14",
        finishtop: "Hand-Rubbed",
        bracingpattern: "Neck Joint",
        backandsidefinish: "None",
        scalelength: "23",
        fingerboardwidth: "1 11/16",
        topmaterial: "Sitka Spruce",
        neckshape: "Low Oval",
        backmaterial: "HPL",
        case: "Soft Gig Case",
        sidematerial: "HPL",
        electronics: "No",
      },
    ],
  },
  {
    id: 2,
    image:
      "https://theguitarstore.s3.ap-south-1.amazonaws.com/little-series/LXK2.jpg",
    title: "LXK2",
    series: "Little Series",
    price: "$199",
    specs: [
      {
        bodysize: "0-14",
        finishtop: "Hand-Rubbed",
        bracingpattern: "Neck Joint",
        backandsidefinish: "None",
        scalelength: "23",
        fingerboardwidth: "1 11/16",
        topmaterial: "Sitka Spurce",
        neckshape: "Lw Oval",
        backmaterial: "HPL",
        case: "Soft Gig Case",
        sidematerial: "HPL",
        electronics: "No",
      },
    ],
  },
  {
    id: 3,
    image:
      "https://theguitarstore.s3.ap-south-1.amazonaws.com/x-series/D-X1E.jpg",
    title: "D-X1E",
    series: "X-Series",
    price: "$249",
    specs: [
      {
        bodysize: "0-14",
        finishtop: "Hand-Rubbed",
        bracingpattern: "Neck Joint",
        backandsidefinish: "None",
        scalelength: "23",
        fingerboardwidth: "1 11/16",
        topmaterial: "Sitka Spurce",
        neckshape: "Lw Oval",
        backmaterial: "HPL",
        case: "Soft Gig Case",
        sidematerial: "HPL",
        electronics: "No",
      },
    ],
  },
  {
    id: 4,
    image:
      "https://theguitarstore.s3.ap-south-1.amazonaws.com/x-series/D-X2E.jpg",
    title: "D-X2E",
    series: "X-Series",
    price: "$299",
    specs: [
      {
        bodysize: "0-14",
        finishtop: "Hand-Rubbed",
        bracingpattern: "Neck Joint",
        backandsidefinish: "None",
        scalelength: "23",
        fingerboardwidth: "1 11/16",
        topmaterial: "Sitka Spurce",
        neckshape: "Lw Oval",
        backmaterial: "HPL",
        case: "Soft Gig Case",
        sidematerial: "HPL",
        electronics: "No",
      },
    ],
  },
  {
    id: 5,
    image:
      "https://theguitarstore.s3.ap-south-1.amazonaws.com/x-series/DC-X2E.jpg",
    title: "DC-X2E",
    series: "X-Series",
    price: "$359",
    specs: [
      {
        bodysize: "0-14",
        finishtop: "Hand-Rubbed",
        bracingpattern: "Neck Joint",
        backandsidefinish: "None",
        scalelength: "23",
        fingerboardwidth: "1 11/16",
        topmaterial: "Sitka Spurce",
        neckshape: "Lw Oval",
        backmaterial: "HPL",
        case: "Soft Gig Case",
        sidematerial: "HPL",
        electronics: "No",
      },
    ],
  },
  {
    id: 6,
    image:
      "https://theguitarstore.s3.ap-south-1.amazonaws.com/x-series/000-X2E.jpg",
    title: "000-X2E",
    series: "X-Series",
    price: "$399",
    specs: [
      {
        bodysize: "0-14",
        finishtop: "Hand-Rubbed",
        bracingpattern: "Neck Joint",
        backandsidefinish: "None",
        scalelength: "23",
        fingerboardwidth: "1 11/16",
        topmaterial: "Sitka Spurce",
        neckshape: "Lw Oval",
        backmaterial: "HPL",
        case: "Soft Gig Case",
        sidematerial: "HPL",
        electronics: "No",
      },
    ],
  },
  {
    id: 7,
    image:
      "https://theguitarstore.s3.ap-south-1.amazonaws.com/x-series/OMC-X1E.jpg",
    title: "OMC-X1E",
    series: "X-Series",
    price: "$359",
    specs: [
      {
        bodysize: "0-14",
        finishtop: "Hand-Rubbed",
        bracingpattern: "Neck Joint",
        backandsidefinish: "None",
        scalelength: "23",
        fingerboardwidth: "1 11/16",
        topmaterial: "Sitka Spurce",
        neckshape: "Lw Oval",
        backmaterial: "HPL",
        case: "Soft Gig Case",
        sidematerial: "HPL",
        electronics: "No",
      },
    ],
  },
  {
    id: 8,
    image:
      "https://theguitarstore.s3.ap-south-1.amazonaws.com/standard-series/D-45.jpg",
    title: "D-45",
    series: "Standard Series",
    price: "$459",
    specs: [
      {
        bodysize: "0-14",
        finishtop: "Hand-Rubbed",
        bracingpattern: "Neck Joint",
        backandsidefinish: "None",
        scalelength: "23",
        fingerboardwidth: "1 11/16",
        topmaterial: "Sitka Spurce",
        neckshape: "Lw Oval",
        backmaterial: "HPL",
        case: "Soft Gig Case",
        sidematerial: "HPL",
        electronics: "No",
      },
    ],
  },
  {
    id: 9,
    image:
      "https://theguitarstore.s3.ap-south-1.amazonaws.com/standard-series/D-28.jpg",
    title: "D-28",
    series: "Standard Series",
    price: "$399",
    specs: [
      {
        bodysize: "0-14",
        finishtop: "Hand-Rubbed",
        bracingpattern: "Neck Joint",
        backandsidefinish: "None",
        scalelength: "23",
        fingerboardwidth: "1 11/16",
        topmaterial: "Sitka Spurce",
        neckshape: "Lw Oval",
        backmaterial: "HPL",
        case: "Soft Gig Case",
        sidematerial: "HPL",
        electronics: "No",
      },
    ],
  },
  {
    id: 10,
    image:
      "https://theguitarstore.s3.ap-south-1.amazonaws.com/standard-series/0-18.jpg",
    title: "0-18",
    series: "Standard Series",
    price: "$459",
    specs: [
      {
        bodysize: "0-14",
        finishtop: "Hand-Rubbed",
        bracingpattern: "Neck Joint",
        backandsidefinish: "None",
        scalelength: "23",
        fingerboardwidth: "1 11/16",
        topmaterial: "Sitka Spurce",
        neckshape: "Lw Oval",
        backmaterial: "HPL",
        case: "Soft Gig Case",
        sidematerial: "HPL",
        electronics: "No",
      },
    ],
  },
  {
    id: 11,
    image:
      "https://theguitarstore.s3.ap-south-1.amazonaws.com/standard-series/000-18.jpg",
    title: "000-18",
    series: "Standard Series",
    price: "$599",
    specs: [
      {
        bodysize: "0-14",
        finishtop: "Hand-Rubbed",
        bracingpattern: "Neck Joint",
        backandsidefinish: "None",
        scalelength: "23",
        fingerboardwidth: "1 11/16",
        topmaterial: "Sitka Spurce",
        neckshape: "Lw Oval",
        backmaterial: "HPL",
        case: "Soft Gig Case",
        sidematerial: "HPL",
        electronics: "No",
      },
    ],
  },
  {
    id: 12,
    image:
      "https://theguitarstore.s3.ap-south-1.amazonaws.com/modern-deluxe-series/D-42-modern-deluxe.jpg",
    title: "D-45 Modern Deluxe",
    series: "Modern Deluxe Series",
    price: "$799",
    specs: [
      {
        bodysize: "0-14",
        finishtop: "Hand-Rubbed",
        bracingpattern: "Neck Joint",
        backandsidefinish: "None",
        scalelength: "23",
        fingerboardwidth: "1 11/16",
        topmaterial: "Sitka Spurce",
        neckshape: "Lw Oval",
        backmaterial: "HPL",
        case: "Soft Gig Case",
        sidematerial: "HPL",
        electronics: "No",
      },
    ],
  },
  {
    id: 13,
    image:
      "https://theguitarstore.s3.ap-south-1.amazonaws.com/modern-deluxe-series/D-45-modern-deluxe.jpg",
    title: "D-28 Modern Deluxe",
    series: "Modern Deluxe Series",
    price: "$899",
    specs: [
      {
        bodysize: "0-14",
        finishtop: "Hand-Rubbed",
        bracingpattern: "Neck Joint",
        backandsidefinish: "None",
        scalelength: "23",
        fingerboardwidth: "1 11/16",
        topmaterial: "Sitka Spurce",
        neckshape: "Lw Oval",
        backmaterial: "HPL",
        case: "Soft Gig Case",
        sidematerial: "HPL",
        electronics: "No",
      },
    ],
  },
  {
    id: 14,
    image:
      "https://theguitarstore.s3.ap-south-1.amazonaws.com/modern-deluxe-series/00-28-modern-deluxe.jpg",
    title: "0-18 Modern Deluxe",
    series: "Modern Deluxe Series",
    price: "$699",
    specs: [
      {
        bodysize: "0-14",
        finishtop: "Hand-Rubbed",
        bracingpattern: "Neck Joint",
        backandsidefinish: "None",
        scalelength: "23",
        fingerboardwidth: "1 11/16",
        topmaterial: "Sitka Spurce",
        neckshape: "Lw Oval",
        backmaterial: "HPL",
        case: "Soft Gig Case",
        sidematerial: "HPL",
        electronics: "No",
      },
    ],
  },
  {
    id: 15,
    image:
      "https://theguitarstore.s3.ap-south-1.amazonaws.com/modern-deluxe-series/000-42-modern-deluxe.jpg",
    title: "000-18 Modern Deluxe",
    series: "Modern Deluxe Series",
    price: "$799",
    specs: [
      {
        bodysize: "0-14",
        finishtop: "Hand-Rubbed",
        bracingpattern: "Neck Joint",
        backandsidefinish: "None",
        scalelength: "23",
        fingerboardwidth: "1 11/16",
        topmaterial: "Sitka Spurce",
        neckshape: "Lw Oval",
        backmaterial: "HPL",
        case: "Soft Gig Case",
        sidematerial: "HPL",
        electronics: "No",
      },
    ],
  },
];
